title: H. Son
first_name: Huigyoeng
middle_name: ""
last_name: Son
contact_note: "E-mail: gyoeng94@gmail.com or gyoengist@gm.gist.ac.kr"
description: "I'm an undergraduate student at GIST (2022-Present). I focus on AI and computer vision, particularly on extracting meaningful insights from medical image data."
keywords: ""
lang: en
icon: "📄"

url: "https://gyoenge.github.io"
baseurl: ""
last_updated: false
impressum_path: ""
back_to_top: true

blog_name: "H. Son"
blog_description: "Personal studies related to Vision and Medical AI."

serve_og_meta: false
serve_schema_org: false
og_image: ""

google_analytics: ""
cronitor_analytics: ""
pirsch_analytics: ""
openpanel_analytics: ""
google_site_verification: ""
bing_site_verification: ""

giscus:
  repo: ""
  repo_id: ""
  category: "Comments"
  category_id: ""
  mapping: "title"
  strict: 1
  reactions_enabled: 1
  input_position: "bottom"
  dark_theme: "dark"
  light_theme: "light"
  emit_metadata: 0
  lang: "en"

disqus_shortname: ""

external_sources: []

scholar:
  last_name: [Son]
  first_name: [Huigyoeng, H.]
